trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - docs/*

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  projects: '**/*.csproj'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: BuildJob
        displayName: 'Build Application'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 8 SDK'
            inputs:
              packageType: 'sdk'
              version: '8.x'

          - task: NodeTool@0
            displayName: 'Use Node.js'
            inputs:
              versionSpec: '18.x'

          - task: NuGetCommand@2
            displayName: 'Restore NuGet packages'
            inputs:
              restoreSolution: '$(solution)'

          - task: Npm@1
            displayName: 'Install frontend dependencies'
            inputs:
              command: 'install'
              workingDir: 'src/frontend'

          - task: DotNetCoreCLI@2
            displayName: 'Build .NET solution'
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration $(buildConfiguration)'

          - task: Npm@1
            displayName: 'Build React application'
            inputs:
              command: 'custom'
              workingDir: 'src/frontend'
              customCommand: 'run build'

          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: 'test'
              projects: '**/*Tests.csproj'
              arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" --logger trx'

          - task: Npm@1
            displayName: 'Run frontend tests'
            inputs:
              command: 'custom'
              workingDir: 'src/frontend'
              customCommand: 'run test:ci'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

          - task: PublishTestResults@2
            displayName: 'Publish test results'
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: '**/*.trx'

  - stage: Security
    displayName: 'Security Scanning'
    jobs:
      - job: SecurityScanJob
        displayName: 'Security Analysis'
        steps:
          - task: SonarCloudPrepare@1
            displayName: 'Prepare SonarCloud analysis'
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'your-org'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'recruitment-crm-ats'
              cliProjectName: 'Recruitment CRM ATS'

          - task: DotNetCoreCLI@2
            displayName: 'Build for SonarCloud'
            inputs:
              command: 'build'
              projects: '$(solution)'

          - task: SonarCloudAnalyze@1
            displayName: 'Run SonarCloud analysis'

          - task: SonarCloudPublish@1
            displayName: 'Publish SonarCloud results'

          - task: WhiteSource@21
            displayName: 'Dependency vulnerability scan'
            inputs:
              whiteSourceServiceConnection: 'WhiteSource'

  - stage: Package
    displayName: 'Package Artifacts'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: PackageJob
        displayName: 'Create deployment packages'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Publish Azure Functions'
            inputs:
              command: 'publish'
              projects: '**/Functions/*.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/functions'

          - task: ArchiveFiles@2
            displayName: 'Archive frontend build'
            inputs:
              rootFolderOrFile: 'src/frontend/dist'
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifacts'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'


